Repository AndreasPB/si-mandatory1, pull requests merged in 2022-06, with the labels that each got.

#33 Add fix for sveltekit breaking change
  web/src/app.html
Labels: bug

#1 Validating jwt's in the backend
  api/app/config.py
  api/app/main.py
  api/poetry.lock
  api/pyproject.toml
Labels: enhancement

#35 Add expire to jwt
  api/app/main.py
Labels: enhancement

#37 Add JWT to header for mitid fetches
  api/app/main.py
  web/src/components/registerForm.svelte
  web/src/components/userTable.svelte
Labels: enhancement

#39 Add missing header in read-messages endpoint
  api/app/main.py
  web/src/components/messageForm.svelte
Labels: bug, enhancement

#40 Comment out fatsms functionality
  api/app/main.py
Labels: enhancement
